[build]
  publish = "out"
  command = "pnpm run build"

# Environment variables
[build.environment]
  NODE_VERSION = "20.19.5"
  NPM_FLAGS = "--version"
  PNPM_VERSION = "latest"

# Cache busting and security headers
[[headers]]
  for = "/app.js"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/styles.css"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/"
  [headers.values]
    cache-control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
